### ISSUE TITLE
Excessive failures and solve times

### ISSUE THREAD

**Issue by Plootie** [elcattivo/CloudFlareUtilities#42]
Firstly if this has been answered in any of the previous issues i'm very sorry, i did read through them but those issues don't seem to be the same as what i'm experiencing. This library was working great for me for a few days and i loved it, no need for node.js and simple to use but yesterday i just kept getting clearance fails. i decided to try again the next day but kept getting clearance fails again so i set retries to 9 and delay to 10,000 as a last ditch effort and while it did eventually work it took 90 seconds (92946ms exactly) to get to the page which isn't particularly great. My test code is [here](https://hastebin.com/ikotigarad.cs)

**Comment by Bleialf** [comment]
Whats the website you are trying to open?

**Comment by Plootie** [comment]
Its in the test code but its https://kissanime.ru

**Comment by Bleialf** [comment]
@Plootie you got the s-parameter there. try my S-Parameter branch with a delay of 4000ms!

https://github.com/Bleialf/CloudFlareUtilities/tree/S-Parameter

**Comment by Eric898989** [comment]
After some trials, I noticed: 

- S parameter has to be Uri.EscapeDataString, otherwise even if the calcultated answer is fine, the request will fail "randomly". 
- if you use User-Agent Client 1.0, you get both success and failure events... better to put a recent standard user-agent in the system instead of Client 1.0
- if you also add the following headers Accept, Referer and Upgrade-Insecure-Requests
```
if (response.RequestMessage.RequestUri != null)
                clearanceRequest.Headers.Add("Referer", response.RequestMessage.RequestUri.ToString());

 clearanceRequest.Headers.Add("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8");
 clearanceRequest.Headers.Add("Upgrade-Insecure-Requests", "1");
```
It appears to finally give a 100% rate from my trials.

I added a pull request implementing all of these #43 (big thanks to  @Bleialf and @Zaczero)
